### ISSUE TITLE
Documentation todo

### ISSUE THREAD

**Issue by ChrisTerBeke** [PRINTR3D/documentation#24]
List of things to do for the public documentation

- [ ] Update client API docs
- [ ] Add coding examples for 3D SDK
- [ ] Add a global introduction
- [ ] Remove design guidelines (for now)
- [ ] Filter Katana docs
- [ ] Restructure Katana docs
- [ ] Update API auth docs (make easier to understand, add more code samples)
- [ ] Update API resource docs (copy from internal API docs)
- [ ] Move client beta guides to client section
- [ ] Remove apps section (for now)
- [ ] Remove issue pages and make a single 'report issue' page
